// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoxWzqOuincc4sGDYlXXkTGOaW0EgqdsE',
    appId: '1:1030751646168:web:6b9bc7c20286569957c2ad',
    messagingSenderId: '1030751646168',
    projectId: 'data-region-454715-q2',
    authDomain: 'data-region-454715-q2.firebaseapp.com',
    storageBucket: 'data-region-454715-q2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVpbJ2YQRF4raegqV1qFNO5CurPmf8WU',
    appId: '1:1030751646168:android:390258913b07c60457c2ad',
    messagingSenderId: '1030751646168',
    projectId: 'data-region-454715-q2',
    storageBucket: 'data-region-454715-q2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3DzQp7AAGZrEWqkSgovsEcrvAwHOn1g',
    appId: '1:1030751646168:ios:ce57fd8888c352f057c2ad',
    messagingSenderId: '1030751646168',
    projectId: 'data-region-454715-q2',
    storageBucket: 'data-region-454715-q2.firebasestorage.app',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3DzQp7AAGZrEWqkSgovsEcrvAwHOn1g',
    appId: '1:1030751646168:ios:ce57fd8888c352f057c2ad',
    messagingSenderId: '1030751646168',
    projectId: 'data-region-454715-q2',
    storageBucket: 'data-region-454715-q2.firebasestorage.app',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoxWzqOuincc4sGDYlXXkTGOaW0EgqdsE',
    appId: '1:1030751646168:web:be0feac8c7de6b9257c2ad',
    messagingSenderId: '1030751646168',
    projectId: 'data-region-454715-q2',
    authDomain: 'data-region-454715-q2.firebaseapp.com',
    storageBucket: 'data-region-454715-q2.firebasestorage.app',
  );
}
